### PR TITLE
option `noGCPLogging` deprecated, new option `GCPLogging` should be u…

### PR DESCRIPTION
**Pull request by darkdarkdragon**
…sed instead

GCP logging now off by default

### CODE REVIEW

**Comment by j0sh** [comment]
Some of the config options have a very helpful deprecation warning if they are used when they shouldn't. Should something be added for `noGCPLogging` ?

Also, would be good to document this option and what the effects are (eg, allows downloading logs from Docker directly)

**Comment by darkdarkdragon** [comment]
@j0sh added deprecation message and added documentation to readme

**Comment by j0sh** [comment]
Looks good to me, thanks! Will let @ya7ya have the final say here in reviewing

**Review by ya7ya — APPROVED** [review]
LGTM :ship:, thanks for the deprecation msg, very helpful

**Pull request merged**
