### PR TITLE
minor fixes

### PR DESCRIPTION
**Pull request by ya7ya**
- [x] change the livepeer overview default timerange to 30 mins

### CODE REVIEW

**Comment by darkdarkdragon** [comment]
@ya7ya Github saying this branch has conflict that needs to be resolved

**Comment by ya7ya** [comment]
@darkdarkdragon I resolved the conflict :+1:

**Comment by darkdarkdragon** [comment]
@ya7ya can you please rebase it on top of current master?

**Comment by ya7ya** [comment]
@darkdarkdragon I rebased it :+1:

**Review by darkdarkdragon — APPROVED** [review]
LGTM 🚢

**Pull request merged**
