### PR TITLE
Integrates new streamer

### PR DESCRIPTION
**Pull request by darkdarkdragon**
Integrates new streamer
Adds `test` command - allows to stream using new streamer and check success rate
Changes configuration so for every service own VM gets created

### CODE REVIEW

**Comment by darkdarkdragon** [comment]
@ya7ya One thing I've not changed - is multi-region config (`zones` flag). I not sure how it should work, so I've not touched. Please check it in.

**Review by ya7ya — APPROVED** [review]

**Comment by ya7ya** [comment]
hey @darkdarkdragon , How do you go about spreading `-s` streams to broadcasters, I can only stream to `broadcaster_0` ?? 😕

**Comment by darkdarkdragon** [comment]
@ya7ya Just create same number of streamers as number of broadcasters (btw, I'm using `n1-standard-1` for streamer)
Or change algorithm by yourself. If you will not changes this, I'll do this later (just didn't have use case for it till now)

**Comment by ya7ya** [comment]
@darkdarkdragon Yeah, i used the same number of streamers as broadcasters, Thanks for the tip 👍

**Pull request merged**
